# Generated by Django 5.1.6 on 2025-12-20 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_timestamp', models.DateTimeField(help_text='Original event create timestamp')),
                ('edit_timestamp', models.DateTimeField(help_text='Original event edit timestamp', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
            ],
            options={
                'db_table': 'api_conversarion',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_timestamp', models.DateTimeField(help_text='Original event create timestamp')),
                ('edit_timestamp', models.DateTimeField(help_text='Original event edit timestamp', null=True)),
                ('direction', models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received')], max_length=8)),
                ('content', models.TextField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.conversation')),
            ],
            options={
                'db_table': 'api_message',
            },
        ),
    ]
