# Generated by Django 5.1.6 on 2025-12-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='edit_timestamp',
            field=models.DateTimeField(help_text='Original event edit timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='edit_timestamp',
            field=models.DateTimeField(help_text='Original event edit timestamp', null=True),
        ),
    ]
