# Generated by Django 5.1.6 on 2025-12-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='log',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='log',
            name='edit_timestamp',
        ),
        migrations.RemoveField(
            model_name='log',
            name='edited_at',
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
